version: '3.8'

networks:
    laravel:
      name: laravel

services:
  php_apache:
    container_name: laravel_php_8_2_php_apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: laravel_php_8_2_mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=laravel_php_8_2
      #- MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: laravel_php_8_2_phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - laravel

  redis:
    image: redis:7.2.1
    container_name: laravel_php_8_2_redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - laravel

  npm:
    image: node:20.11.0
    container_name: laravel_php_8_2_npm_20_11_0
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - laravel